# Generated by Django 3.2.7 on 2021-09-30 11:08

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210919_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[webapp.models.MinValueValidator(100)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=30, validators=[webapp.models.MaxValueValidator(30)], verbose_name='Summary'),
        ),
    ]
