# Generated by Django 3.2.7 on 2021-10-08 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210930_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField(blank=True)),
                ('project_name', models.CharField(max_length=30)),
                ('project_summary', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.project'),
        ),
    ]
