# Generated by Django 3.2.7 on 2021-10-08 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20211008_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='task_id',
            new_name='task',
        ),
    ]
