# Generated by Django 3.2.7 on 2021-12-02 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0010_remove_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='IssueCreationTime'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[webapp.models.MinValueValidator(100)], verbose_name='IssueDescription'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='webapp.status', verbose_name='IssueStatus'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=30, validators=[webapp.models.MaxValueValidator(30)], verbose_name='IssueSummary'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='IssueUpdateTime'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateField(blank=True, verbose_name='ProjectFinishDate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=30, verbose_name='ProjectName'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_summary',
            field=models.TextField(verbose_name='ProjectSummary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='ProjectStartDate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='ProjectUsers'),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=20, verbose_name='StatusTitle'),
        ),
        migrations.AlterField(
            model_name='type',
            name='title',
            field=models.CharField(max_length=20, verbose_name='TypeTitle'),
        ),
    ]
