# Generated by Django 3.2.7 on 2021-12-02 10:59

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20211202_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description_en',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[webapp.models.MinValueValidator(100)], verbose_name='IssueDescription'),
        ),
        migrations.AddField(
            model_name='issue',
            name='description_kz',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[webapp.models.MinValueValidator(100)], verbose_name='IssueDescription'),
        ),
        migrations.AddField(
            model_name='issue',
            name='description_ru',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[webapp.models.MinValueValidator(100)], verbose_name='IssueDescription'),
        ),
        migrations.AddField(
            model_name='issue',
            name='summary_en',
            field=models.CharField(max_length=30, null=True, validators=[webapp.models.MaxValueValidator(30)], verbose_name='IssueSummary'),
        ),
        migrations.AddField(
            model_name='issue',
            name='summary_kz',
            field=models.CharField(max_length=30, null=True, validators=[webapp.models.MaxValueValidator(30)], verbose_name='IssueSummary'),
        ),
        migrations.AddField(
            model_name='issue',
            name='summary_ru',
            field=models.CharField(max_length=30, null=True, validators=[webapp.models.MaxValueValidator(30)], verbose_name='IssueSummary'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='ProjectName'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name_kz',
            field=models.CharField(max_length=30, null=True, verbose_name='ProjectName'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='ProjectName'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_summary_en',
            field=models.TextField(null=True, verbose_name='ProjectSummary'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_summary_kz',
            field=models.TextField(null=True, verbose_name='ProjectSummary'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_summary_ru',
            field=models.TextField(null=True, verbose_name='ProjectSummary'),
        ),
        migrations.AddField(
            model_name='status',
            name='title_en',
            field=models.CharField(max_length=20, null=True, verbose_name='StatusTitle'),
        ),
        migrations.AddField(
            model_name='status',
            name='title_kz',
            field=models.CharField(max_length=20, null=True, verbose_name='StatusTitle'),
        ),
        migrations.AddField(
            model_name='status',
            name='title_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='StatusTitle'),
        ),
        migrations.AddField(
            model_name='type',
            name='title_en',
            field=models.CharField(max_length=20, null=True, verbose_name='TypeTitle'),
        ),
        migrations.AddField(
            model_name='type',
            name='title_kz',
            field=models.CharField(max_length=20, null=True, verbose_name='TypeTitle'),
        ),
        migrations.AddField(
            model_name='type',
            name='title_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='TypeTitle'),
        ),
    ]
